minimumReleaseAgeExclude:
  - '@opentui/core-darwin-arm64@0.5.10'
  - '@opentui/core-darwin-x64@0.5.10'
  - '@opentui/core-linux-arm64-musl@0.5.10'
  - '@opentui/core-linux-arm64@0.5.10'
  - '@opentui/core-linux-x64-musl@0.5.10'
  - '@opentui/core-linux-x64@0.5.10'
  - '@opentui/core-win32-arm64@0.5.10'
  - '@opentui/core-win32-x64@0.5.10'
  - '@opentui/core@0.5.10'
  - '@opentui/solid@0.5.10'
